#!/bin/bash

set -e

export TEST_OS=Ubuntu
export TEST_OS_VERSION=14.04
export OBS_USERNAME=pfeiffersz
export OBS_PROJECT_DIR=$OBS_HOME:$OBS_PROJECT:$OBS_MAJOR_VERSION:$OBS_MINOR_VERSION:$OBS_MAINTENANCE_VERSION/$OBS_PACKAGE
